### ISSUE TITLE
Obrazki nie są centrowane

### ISSUE THREAD

**Issue by AzuxDario** [skni-kod/SKNIFrontEnd#28]
Domyślny kod podpowiadany przez edytor artykułów używa Markdowna do wstawiania obrazków. Przez co nie są one scentrowane, a wyrównane do lewej. Wynika to z tego, że Markdown nie obsługuje pozycjonowania.
Obecnie obchodzę to wstawiając obrazek tak
```
<div style="text-align: center; margin: 10px;">
<img src="https://kod.prz.edu.pl/media/gallery/Moc_Odkrywc%C3%B3w_9.jpg" />
<p>Komendy bota</p>
</div> 
```
Aby nie wymuszać od użytkownika wklejania kodu HTML do treści artykułu, proponuję jakiś parser, który wykryje obrazki i sam doda do nich styl `style="text-align: center;"`
Myślę, że obrazki wyrównane do środka będą lepsze w artykułach. Co o tym sądzicie?

**Comment by AzuxDario** [comment]
Powyższy kod centruje od razu podpis pod obrazkiem

**Comment by km2442** [comment]
Problem nie jest taki łatwy do rozwiązania, ten edytor markdowna używany jest również w miejscach, w których tagi html są wyłączone, np. profil użytkownika - nie chcemy XSSów jak jakiś śmieszek się znajdzie. Artykuły tymczasem będą wprowadzane przez zaufane osoby więc tam tagi ustawiłem na włączone.
Jeżeli bym chciał wprowadzić system jaki propnujesz z tagami, trzeba by go wyłączać przy niektórych funkcjonalnościach i używać aktualnego.
Co o tym myślicie?

**Comment by km2442** [comment]
Dobra, udało mi się to ogarnąć
