### ISSUE TITLE
Lepsze oznaczanie końca podglądu

### ISSUE THREAD

**Issue by AzuxDario** [skni-kod/SKNIFrontEnd#30]
Obecnie do oznaczenia końca podglądu używamy znacznika `---readmore---`. Podczas edycji w podglądzie artykułu wyświetla się on po prostu jako ---readmore---.

Myślę, że lepiej byłoby gdyby była to czerwona linia z napisem nad nią `Tutaj kończy się podgląd`.

Zamiast
![obraz](https://user-images.githubusercontent.com/26147393/135523625-a262bdab-4bb1-41b7-9b83-19cc731d2514.png)
To
![obraz](https://user-images.githubusercontent.com/26147393/135524314-5c5d6c0c-9f2c-4150-9c38-d8fdb6fec605.png)
Osiągnąłem to przez to ale pewnie da się lepiej
```html
<p data-source-line="1" style="text-align: center; color: red;">Tutaj kończy się podgląd</p>
<hr style="height:1px;border-top:1px solid #f00"></hr>
````
Co o takiej zmianie sądzicie?
Oczywiście problem może być gdy `---readmore---` nie jest pomiędzy akapitami ale w środku akapitu. Wtedy ta przerwa nie oddaje tego jak finalnie będzie wyglądał artykuł. Więc może po prostu czerwony zwrot `Tutaj kończy się podgląd` zamiast obecnego `---readmore---` w podglądzie?
![obraz](https://user-images.githubusercontent.com/26147393/135525071-bef1bc98-049e-453c-bdc2-c83253741d86.png)

**Comment by km2442** [comment]
Udało się ogarnąć
