### ISSUE TITLE
Na komputerze pasek boczny przesuwa treść

### ISSUE THREAD

**Issue by AzuxDario** [skni-kod/SKNIFrontEnd#33]
Pasek boczny zamiast nachodzić nad treścią jak to jest zwykle zrobione, ścieśnia ją, co nie jest do końca intuicyjne i wygląda dziwnie.
Zwykle takie menu boczne najeżdża nad stronę, a nie w nią.

Normalnie
![obraz](https://user-images.githubusercontent.com/26147393/135528556-e8cf0e02-c375-4dc5-abe5-099ad5f48e53.png)

Ścieśnione
![obraz](https://user-images.githubusercontent.com/26147393/135528583-337936ff-dd43-4bcd-84c7-5fea4a122ab7.png)

**Comment by km2442** [comment]
Zmienione
