### ISSUE TITLE
Hardware przenosi do 404

### ISSUE THREAD

**Issue by AzuxDario** [skni-kod/SKNIFrontEnd#34]
Gdy klikniemy w górnym menu na hardware zostaniemy przeniesieni tam gdzie powinniśmy. Gdy jednak zrobimy to z paska bocznego dostaniemy 404:
![obraz](https://user-images.githubusercontent.com/26147393/135528928-a2094110-3cdb-45c7-8793-90ab6b341c1b.png)

Kroki do odtworzenia:
1. Zaloguj się
2. Otwórz pasek boczny
3. Kliknij w hardware
4. Otrzymasz 404

**Comment by AzuxDario** [comment]
Hardware z paska bocznego przenosi na https://kod.prz.edu.pl/#/hardware, a potem na https://kod.prz.edu.pl/#/404
Hardware z menu górnego przenosi na https://kod.prz.edu.pl/#/hardware/1

**Comment by AzuxDario** [comment]
Co ciekawe działa gdy z paska bocznego otworzymy hardware w nowej karcie, a nie przez kliknięcie.

**Comment by km2442** [comment]
Naprawiłem, wjedzie przy najbliższym update stronki
