### ISSUE TITLE
Artykuł widmo, gdy nie ma obrazka w galerii

### ISSUE THREAD

**Issue by AzuxDario** [skni-kod/SKNIFrontEnd#49]
Jeśli w galerii nie ma ani jednego obrazka, artykuł nie ma miniaturki i staje się artykułem widmo. Wciąż zajmuje miejsce na stronie (screen niżej pokazuje 5 artykułów pomimo, że backend zwrócił 6) ale jest niewidoczny.
![obraz](https://user-images.githubusercontent.com/26147393/142884290-b7022500-a2ab-4428-95ab-1babf5815ddc.png)

**Comment by SzateX** [comment]
Zalecałbym podstawienie w przypadku braku obrazka, placeholdera, bo inaczej np. na mojej bazie deweloperskiej dzieje się tak:

![obraz](https://user-images.githubusercontent.com/10698770/143314506-57ff62e7-b3a0-43e7-b0f3-838eb3a0e779.png)
